### PR TITLE
Fix/clip post-lapse stability

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
related PR:
- https://github.com/open-spaced-repetition/fsrs-rs/pull/257

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
> When the long-term scheduler is enabled, should 
> 𝑤
> 17
> ×
> 𝑤
> 18
>  be equal to 0?

Yes. So exp(w[17] * w[18]) = 1.

**Comment by ishiko732** [comment]
> So exp(w[17] * w[18]) = 1.

I understand, but after switching to the long-term scheduler, $$w_{17}$$ and $$w_{18}$$ are not necessarily 0. Should their values be determined based on `p.EnableShortTerm`?

```go
var newSMin float64
if p.EnableShortTerml {
    newSMin = s / math.Exp(p.W[17]*p.W[18])
} else {
    newSMin = s
}
```

**Comment by L-M-Sherlock** [comment]
Right. I have another idea: when `EnableShortTerm` is false, reset `W[17]` and `W[18]` to zero. What about that?

**Comment by ishiko732** [comment]
> I have another idea: when `EnableShortTerm` is false, reset `W[17]` and `W[18]` to zero. What about that?

I think that continuously switching schedulers might confuse developers, as they may not understand why `W[17]` and `W[18]` are suddenly set to zero. :(

**Comment by L-M-Sherlock** [comment]
OK, I will update the PR based on your suggestion tomorrow.

**Comment by L-M-Sherlock** [comment]
@ishiko732 cc

**Review by ishiko732 — APPROVED** [review]
LGTM

**Pull request merged**
